# GitHub Sponsors-enabled usernames (up to 4)
github: [peterclemenko]

# Patreon username
# patreon: user

# Open Collective username
# open_collective: user

# Ko-fi username
# ko_fi: user

# Tidelift platform-name/package-name
# tidelift: npm/babel

# Community Bridge project-name
# community_bridge: cloud-foundry

# Liberapay username
# liberapay: user

# IssueHunt username
# issuehunt: user

# LFX Crowdfunding project-name
# lfx_crowdfunding: cloud-foundry

# Polar username
# polar: user

# Buy Me a Coffee username
# buy_me_a_coffee: user

# Custom URLs (up to 4)
custom: ['https://example1.com', 'https://example2.com', 'https://example3.com', 'https://example4.com']
